"""initial migration

Revision ID: bfaf769cd081
Revises: 
Create Date: 2023-01-28 17:26:19.946819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfaf769cd081'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surra_number', sa.Integer(), nullable=True),
    sa.Column('aya_number', sa.Integer(), nullable=True),
    sa.Column('audio_file_name', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('final_transcription', sa.String(), nullable=True),
    sa.Column('label', postgresql.ENUM('correct', 'in_correct', 'not_related_quran', 'not_match_aya', 'multiple_aya', name='label_enum'), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('user_role', postgresql.ENUM('annotator', 'admin', 'recitingApp', name='user_role_enum'), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('validate_correctness_exam_correct_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('validate_correctness_cts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.String(), nullable=True),
    sa.Column('surra_number', sa.Integer(), nullable=True),
    sa.Column('aya_number', sa.Integer(), nullable=True),
    sa.Column('audio_file_name', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('surra_aya', sa.String(), nullable=True),
    sa.Column('golden', sa.Boolean(), nullable=True),
    sa.Column('label', postgresql.ENUM('correct', 'in_correct', 'not_related_quran', 'not_match_aya', 'multiple_aya', name='label_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validate_correctness_cts_id'), 'validate_correctness_cts', ['id'], unique=False)
    op.create_table('validate_correctness_cts_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validate_correctness_ct_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('test', sa.Boolean(), nullable=True),
    sa.Column('label', postgresql.ENUM('correct', 'in_correct', 'not_related_quran', 'not_match_aya', 'multiple_aya', name='label_enum'), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validate_correctness_ct_id'], ['validate_correctness_cts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validate_correctness_cts_users')
    op.drop_index(op.f('ix_validate_correctness_cts_id'), table_name='validate_correctness_cts')
    op.drop_table('validate_correctness_cts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
