name: Quran Annotation Docker Image CI

on:
  push:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set env BRANCH
      run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
    - name: Set env Dev
      run: |
        if [[ $BRANCH == 'develop' && $GITHUB_EVENT_NAME == 'push' ]]; then
            echo "Dev=true" >> "$GITHUB_ENV"
        else
            echo "Dev=false" >> "$GITHUB_ENV"
        fi

    - name: Build and push - develop
      if: env.Dev == 'true'
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: raghadsy/quran-annotation:${{ github.sha }}
    - name: Build and push - main
      if: env.Dev != 'true'
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: raghadsy/quran-annotation-live:${{ github.sha }}