name: Quran Annotation Docker Image CI

on:
  push:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push - develop
      if: contains(github.ref, "develop")
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: raghadsy/quran-annotation:${{ github.sha }}
    - name: Build and push - Production
      if: contains(github.ref, "main")
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: raghadsy/quran-annotation-prod:${{ github.sha }}